name: Publish app & update platform
on:
  push:
    branches: [ "main" ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_TOKEN }}
    - run: |
        git config --global user.name 'devopshelper4u'
        git config --global user.email 'devops.helper.4u@gmail.com'
        npm version patch -m "[RELEASE] %s"
        git push
  
  create-pkg:
    needs: update-version
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
    - uses: actions/checkout@v3
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: cat package.json
    - run: npm ci
    - run: npm publish
    - run: APP_VERSION=$(jq --raw-output '.version' package.json)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MY_TOKEN }}
        TEMP_VERSION: "1.0.0"

  # Update app version in app-platform
  update-platform:
    needs: [update-version, create-pkg]
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
    - name: Get other repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_TOKEN }}
        repository: devopshelper4u/app-platform
        ref: 'main'
        path: ./repo2
    - run: |
        echo -e "App version : $APP_VERSION"
        cd ./repo2
        jq ".myapps.internalapps.\"@devopshelper4u/app1\".version = \"$APP_VERSION\"" config/config.json > config/temp_file.json
        rm -rf config/config.json
        mv config/temp_file.json config/config.json
        git config user.email "devops.helper.4u@gmail.com"
        git config user.name "devopshelper4u"
        git add .
        git commit -m "Updated version for app 'app1'. New version - $APP_VERSION"
        git push origin main
