name: Publish Package & update dependent repos 1
# on:
#   release:
#     types: [created]
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
#      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_TOKEN }}
          
      # Update app version in app-platform
      - name: Get other repo
        env:
          TEMP_VERSION: "1.0.0"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          repository: devopshelper4u/app-platform
          ref: 'main'
          path: ./repo2
      - run: |
          APP_VERSION=$(jq --raw-output '.version' package.json)
          echo -e "Version : $APP_VERSION"
          cd ./repo2
          echo "1"
          jq ".myapps.internalapps.\"@devopshelper4u/app1\".version = \"$APP_VERSION\"" config/config.json > config/config.json
          echo "222"
          git config user.email "devops.helper.4u@gmail.com"
          git config user.name "devopshelper4u"
          echo "3333"
          git add .
          git commit -m "Updated version as other repo got updated - %s"
          echo "4444"
          git push origin main
        
